DROP TABLE IF EXISTS objtrackerT_Documentation ,
 objtrackerT_InstallState ,
 objtrackerT_Measurement ,
 objtrackerT_Target ,
 objtrackerT_Objective ,
 objtrackerT_Person ,
 objtrackerT_Department,
 objtrackerT_ObjectiveType ,
 objtrackerT_Frequency ,
 objtrackerT_MetricType ,
 objtrackerT_FiscalYear,
 objtrackerT_FyCalendar,
 objtrackerT_AuditIndex,
 objtrackerT_Audit,
 objtrackerT_AuditColumn,
 objtrackerT_AuditTable,
 objtrackerT_Organization ;
